//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyChat.Web.CozyChatServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatRoom", Namespace="http://schemas.datacontract.org/2004/07/CozyChat.Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ChatRoom : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CozyChat.Web.CozyChatServiceProxy.User CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCurrentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CozyChat.Web.CozyChatServiceProxy.Message[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CozyChat.Web.CozyChatServiceProxy.User[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CozyChat.Web.CozyChatServiceProxy.User Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatorId {
            get {
                return this.CreatorIdField;
            }
            set {
                if ((this.CreatorIdField.Equals(value) != true)) {
                    this.CreatorIdField = value;
                    this.RaisePropertyChanged("CreatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCurrent {
            get {
                return this.IsCurrentField;
            }
            set {
                if ((this.IsCurrentField.Equals(value) != true)) {
                    this.IsCurrentField = value;
                    this.RaisePropertyChanged("IsCurrent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CozyChat.Web.CozyChatServiceProxy.Message[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CozyChat.Web.CozyChatServiceProxy.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/CozyChat.Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CozyChat.Web.CozyChatServiceProxy.ChatRoom[] ChatRoomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastSeenDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CozyChat.Web.CozyChatServiceProxy.Message[] ReceivedMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegisteredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CozyChat.Web.CozyChatServiceProxy.Message[] SentMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CozyChat.Web.CozyChatServiceProxy.ChatRoom[] ChatRooms {
            get {
                return this.ChatRoomsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChatRoomsField, value) != true)) {
                    this.ChatRoomsField = value;
                    this.RaisePropertyChanged("ChatRooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastSeenDate {
            get {
                return this.LastSeenDateField;
            }
            set {
                if ((this.LastSeenDateField.Equals(value) != true)) {
                    this.LastSeenDateField = value;
                    this.RaisePropertyChanged("LastSeenDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CozyChat.Web.CozyChatServiceProxy.Message[] ReceivedMessages {
            get {
                return this.ReceivedMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivedMessagesField, value) != true)) {
                    this.ReceivedMessagesField = value;
                    this.RaisePropertyChanged("ReceivedMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegisteredDate {
            get {
                return this.RegisteredDateField;
            }
            set {
                if ((this.RegisteredDateField.Equals(value) != true)) {
                    this.RegisteredDateField = value;
                    this.RaisePropertyChanged("RegisteredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CozyChat.Web.CozyChatServiceProxy.Message[] SentMessages {
            get {
                return this.SentMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.SentMessagesField, value) != true)) {
                    this.SentMessagesField = value;
                    this.RaisePropertyChanged("SentMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/CozyChat.Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CozyChatServiceProxy.ICozyChatService")]
    public interface ICozyChatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/GetChatRooms", ReplyAction="http://tempuri.org/ICozyChatService/GetChatRoomsResponse")]
        CozyChat.Web.CozyChatServiceProxy.ChatRoom[] GetChatRooms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/GetChatRooms", ReplyAction="http://tempuri.org/ICozyChatService/GetChatRoomsResponse")]
        System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.ChatRoom[]> GetChatRoomsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/CreateChatRoom", ReplyAction="http://tempuri.org/ICozyChatService/CreateChatRoomResponse")]
        CozyChat.Web.CozyChatServiceProxy.ChatRoom CreateChatRoom(int userId, string chatRoomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/CreateChatRoom", ReplyAction="http://tempuri.org/ICozyChatService/CreateChatRoomResponse")]
        System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.ChatRoom> CreateChatRoomAsync(int userId, string chatRoomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/DeleteChatRoom", ReplyAction="http://tempuri.org/ICozyChatService/DeleteChatRoomResponse")]
        bool DeleteChatRoom(int userId, int chatRoomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/DeleteChatRoom", ReplyAction="http://tempuri.org/ICozyChatService/DeleteChatRoomResponse")]
        System.Threading.Tasks.Task<bool> DeleteChatRoomAsync(int userId, int chatRoomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/SubscribeUserForRoom", ReplyAction="http://tempuri.org/ICozyChatService/SubscribeUserForRoomResponse")]
        bool SubscribeUserForRoom(int userId, int roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/SubscribeUserForRoom", ReplyAction="http://tempuri.org/ICozyChatService/SubscribeUserForRoomResponse")]
        System.Threading.Tasks.Task<bool> SubscribeUserForRoomAsync(int userId, int roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/UnSubscribeUserForRoom", ReplyAction="http://tempuri.org/ICozyChatService/UnSubscribeUserForRoomResponse")]
        bool UnSubscribeUserForRoom(int userId, int roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/UnSubscribeUserForRoom", ReplyAction="http://tempuri.org/ICozyChatService/UnSubscribeUserForRoomResponse")]
        System.Threading.Tasks.Task<bool> UnSubscribeUserForRoomAsync(int userId, int roomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/GetSubscribedChatRooms", ReplyAction="http://tempuri.org/ICozyChatService/GetSubscribedChatRoomsResponse")]
        CozyChat.Web.CozyChatServiceProxy.ChatRoom[] GetSubscribedChatRooms(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/GetSubscribedChatRooms", ReplyAction="http://tempuri.org/ICozyChatService/GetSubscribedChatRoomsResponse")]
        System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.ChatRoom[]> GetSubscribedChatRoomsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/GetUsersSubscribedToChatRoom", ReplyAction="http://tempuri.org/ICozyChatService/GetUsersSubscribedToChatRoomResponse")]
        CozyChat.Web.CozyChatServiceProxy.User[] GetUsersSubscribedToChatRoom(int chatRoomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/GetUsersSubscribedToChatRoom", ReplyAction="http://tempuri.org/ICozyChatService/GetUsersSubscribedToChatRoomResponse")]
        System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.User[]> GetUsersSubscribedToChatRoomAsync(int chatRoomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/GetMessagesForChatRoom", ReplyAction="http://tempuri.org/ICozyChatService/GetMessagesForChatRoomResponse")]
        CozyChat.Web.CozyChatServiceProxy.Message[] GetMessagesForChatRoom(int chatRoomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/GetMessagesForChatRoom", ReplyAction="http://tempuri.org/ICozyChatService/GetMessagesForChatRoomResponse")]
        System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.Message[]> GetMessagesForChatRoomAsync(int chatRoomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/RegisterUser", ReplyAction="http://tempuri.org/ICozyChatService/RegisterUserResponse")]
        CozyChat.Web.CozyChatServiceProxy.User RegisterUser(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/RegisterUser", ReplyAction="http://tempuri.org/ICozyChatService/RegisterUserResponse")]
        System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.User> RegisterUserAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/CheckLogin", ReplyAction="http://tempuri.org/ICozyChatService/CheckLoginResponse")]
        CozyChat.Web.CozyChatServiceProxy.User CheckLogin(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/CheckLogin", ReplyAction="http://tempuri.org/ICozyChatService/CheckLoginResponse")]
        System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.User> CheckLoginAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/SendMessage", ReplyAction="http://tempuri.org/ICozyChatService/SendMessageResponse")]
        bool SendMessage(int senderId, string content, System.Nullable<int> userId, System.Nullable<int> chatRoomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICozyChatService/SendMessage", ReplyAction="http://tempuri.org/ICozyChatService/SendMessageResponse")]
        System.Threading.Tasks.Task<bool> SendMessageAsync(int senderId, string content, System.Nullable<int> userId, System.Nullable<int> chatRoomId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICozyChatServiceChannel : CozyChat.Web.CozyChatServiceProxy.ICozyChatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CozyChatServiceClient : System.ServiceModel.ClientBase<CozyChat.Web.CozyChatServiceProxy.ICozyChatService>, CozyChat.Web.CozyChatServiceProxy.ICozyChatService {
        
        public CozyChatServiceClient() {
        }
        
        public CozyChatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CozyChatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CozyChatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CozyChatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CozyChat.Web.CozyChatServiceProxy.ChatRoom[] GetChatRooms() {
            return base.Channel.GetChatRooms();
        }
        
        public System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.ChatRoom[]> GetChatRoomsAsync() {
            return base.Channel.GetChatRoomsAsync();
        }
        
        public CozyChat.Web.CozyChatServiceProxy.ChatRoom CreateChatRoom(int userId, string chatRoomName) {
            return base.Channel.CreateChatRoom(userId, chatRoomName);
        }
        
        public System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.ChatRoom> CreateChatRoomAsync(int userId, string chatRoomName) {
            return base.Channel.CreateChatRoomAsync(userId, chatRoomName);
        }
        
        public bool DeleteChatRoom(int userId, int chatRoomId) {
            return base.Channel.DeleteChatRoom(userId, chatRoomId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteChatRoomAsync(int userId, int chatRoomId) {
            return base.Channel.DeleteChatRoomAsync(userId, chatRoomId);
        }
        
        public bool SubscribeUserForRoom(int userId, int roomId) {
            return base.Channel.SubscribeUserForRoom(userId, roomId);
        }
        
        public System.Threading.Tasks.Task<bool> SubscribeUserForRoomAsync(int userId, int roomId) {
            return base.Channel.SubscribeUserForRoomAsync(userId, roomId);
        }
        
        public bool UnSubscribeUserForRoom(int userId, int roomId) {
            return base.Channel.UnSubscribeUserForRoom(userId, roomId);
        }
        
        public System.Threading.Tasks.Task<bool> UnSubscribeUserForRoomAsync(int userId, int roomId) {
            return base.Channel.UnSubscribeUserForRoomAsync(userId, roomId);
        }
        
        public CozyChat.Web.CozyChatServiceProxy.ChatRoom[] GetSubscribedChatRooms(int userId) {
            return base.Channel.GetSubscribedChatRooms(userId);
        }
        
        public System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.ChatRoom[]> GetSubscribedChatRoomsAsync(int userId) {
            return base.Channel.GetSubscribedChatRoomsAsync(userId);
        }
        
        public CozyChat.Web.CozyChatServiceProxy.User[] GetUsersSubscribedToChatRoom(int chatRoomId) {
            return base.Channel.GetUsersSubscribedToChatRoom(chatRoomId);
        }
        
        public System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.User[]> GetUsersSubscribedToChatRoomAsync(int chatRoomId) {
            return base.Channel.GetUsersSubscribedToChatRoomAsync(chatRoomId);
        }
        
        public CozyChat.Web.CozyChatServiceProxy.Message[] GetMessagesForChatRoom(int chatRoomId) {
            return base.Channel.GetMessagesForChatRoom(chatRoomId);
        }
        
        public System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.Message[]> GetMessagesForChatRoomAsync(int chatRoomId) {
            return base.Channel.GetMessagesForChatRoomAsync(chatRoomId);
        }
        
        public CozyChat.Web.CozyChatServiceProxy.User RegisterUser(string name, string password) {
            return base.Channel.RegisterUser(name, password);
        }
        
        public System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.User> RegisterUserAsync(string name, string password) {
            return base.Channel.RegisterUserAsync(name, password);
        }
        
        public CozyChat.Web.CozyChatServiceProxy.User CheckLogin(string name, string password) {
            return base.Channel.CheckLogin(name, password);
        }
        
        public System.Threading.Tasks.Task<CozyChat.Web.CozyChatServiceProxy.User> CheckLoginAsync(string name, string password) {
            return base.Channel.CheckLoginAsync(name, password);
        }
        
        public bool SendMessage(int senderId, string content, System.Nullable<int> userId, System.Nullable<int> chatRoomId) {
            return base.Channel.SendMessage(senderId, content, userId, chatRoomId);
        }
        
        public System.Threading.Tasks.Task<bool> SendMessageAsync(int senderId, string content, System.Nullable<int> userId, System.Nullable<int> chatRoomId) {
            return base.Channel.SendMessageAsync(senderId, content, userId, chatRoomId);
        }
    }
}
